name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'mvn'
    - name: Build Squerall
      run: mvn -B package --file pom.xml
    - name: Build Data Loader
      run: cd evaluation/SQLtoNOSQL staging && mvn -B package --file pom.xml
